apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-soknad
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image:  {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8080
  liveness:
    path: /familie/alene-med-barn/soknad/internal/isAlive
    initialDelay: 5
  readiness:
    path: /familie/alene-med-barn/soknad/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://www.nav.no/familie/alene-med-barn/soknad
  accessPolicy:
    outbound:
      external:
        - host: loginservice.nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: ENV
      value: prod
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice.nav.no/login
    - name: UNLEASH_API_URL
      value: https://unleashproxy.nais.oera.no/api/
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
