apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-soknad
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image:  {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8080
  liveness:
    path: /familie/alene-med-barn/soknad/internal/isAlive
    initialDelay: 5
  readiness:
    path: /familie/alene-med-barn/soknad/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: Level4
  tokenx:
    enabled: true
  ingresses:
    - https://familie.dev.nav.no/familie/alene-med-barn/soknad
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-soknad-api
        - application: familie-ef-dokument
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: ENV
      value: dev
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
