apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-soknad
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: navikt/familie-ef-soknad:{{version}}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 9000
  liveness:
    path: /
    initialDelay: 5
  readiness:
    path: /
    initialDelay: 5
  prometheus:
    enabled: false
    path: /metrics
  istio:
    enabled: true
  ingresses:
    - https://familie-ef-soknad.nais.oera-q.local
  vault:
    enabled: false
  webproxy: true
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice-q.nav.no/login
    - name: NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: NAV_TRUSTSTORE_PATH
      value: /var/run/secrets/naisd.io/nav_truststore_path
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: NON-PROD
    - name: UNLEASH_API_URL
      value: https://unleashproxy.nais.oera.no/api/
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
