apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-soknad
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: navikt/familie-ef-soknad:{{version}}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8080
  liveness:
    path: /
  readiness:
    path: /
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://familie-ef-soknad.nais.oera-q.local
  vault:
    enabled: false
  webproxy: true
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice-q.nav.no/login
    - name: UNLEASH_API_URL
      value: https://unleashproxy.nais.oera.no/api/
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
