apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-soknad
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8080
  liveness:
    path: /
  readiness:
    path: /
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://familie-gcp.nav.no/familie/alene-med-barn/soknad
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-soknad-api
      external:
        - host: appres.nav.no
        - host: loginservice.nav.no
        - host: unleashproxy.nais.oera.no
  envFrom:
    - secret: familie
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice.nav.no/login
    - name: UNLEASH_API_URL
      value: https://unleashproxy.nais.oera.no/api/
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi