name: 'Remove old images'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2-5 * * *'

jobs:
  remove-images:
    name: 'Remove old images job'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-ef-soknad/familie-ef-soknad'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-ef-soknad'
          package-type: 'container'
          min-versions-to-keep: 1